name: SonarCloud JS Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci --ignore-scripts --no-audit --prefer-offline

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=st10254797
            -Dsonar.projectKey=ST10254797_insy7314-poe-backend
            -Dsonar.sources=Controllers,Middleware,Models,Routes,utils,app.js,server.js
            -Dsonar.exclusions=node_modules/**,dist/**,build/**,**/*.spec.js,**/*.test.js,.github/**
            -Dsonar.security.enabled=false
            -Dsonar.javascript.security.enabled=false
            -Dsonar.jasmin.enabled=false
            -Dsonar.cpd.exclusions=**/*
            -Dsonar.scm.disabled=true
            -Dsonar.coverage.exclusions=**/*
            -Dsonar.typescript.tsconfigPath=/dev/null
            -Dsonar.log.level=WARN
            -Dsonar.verbose=false